//created on: Jun 11, 2018
package drools.spring.rules

//list any import classes here.
import drools.spring.example.symptom.Symptom;
import drools.spring.example.symptom.SymptomType;
import drools.spring.example.disease.Disease;
import drools.spring.example.disease.DiseaseType;
import drools.spring.example.prescription.Prescription;
import drools.spring.example.medicine.MedicineType;
import drools.spring.example.medicine.Medicine;
import drools.spring.example.medicine.Message;
import drools.spring.example.patient.Patient;
import drools.spring.example.prescription.Prescription;
import java.util.List;
import java.util.Set;
import java.util.HashSet;

//declare any global variables here

global Long nowGlobal;
global java.util.Set stringSet;

rule "Pacijenti sa hronicnim oboljenjima "
agenda-group "reports"
    when
    	$d :Disease( 
	    	$dt: diseaseType, 
	    	$p: patient,
	    	diseaseType != DiseaseType.PREHLADA,
	    	diseaseType != DiseaseType.GROZNICA,
	    	timeStamp  > (nowGlobal - 2*356*24*3600*1000)  
    	)
    	
    	$n: Number (intValue > 5) from accumulate(
        	$dis:Disease( $dt == diseaseType,
        		$p == patient,
        		timeStamp  > (nowGlobal - 2*356*24*3600*1000)
        	), count(1)
        )
    	
    then
    	
	    	stringSet.add(
	    	"Pacijent "+ $p.getName()+ " "+ $p.getSurname() +
	    	" verovatno hornicno boluje od " + $d.getDiseaseType()+
	    	" zato sto je bolovao od nje " + $n+" puta u poslednjih 2 god"
	    	);      
end


rule "Spisak zavisnika "
agenda-group "reports"
    when
    	$p :Patient()
    	$listOfPrescriptions: List() from collect(
        	Prescription(
        		$p == patient,
        		medicine.medicineType == MedicineType.ANALGETIK,
        		disease.timeStamp  > (nowGlobal - 6*30*24*3600*10000)
        	)
        )
    	eval($listOfPrescriptions.size() >= 5)
    	
    	$setDoctors: Set() from accumulate(
            Prescription($d : user) from $listOfPrescriptions,
            init(Set doctors = new HashSet();),
            action(doctors.add($d);),
            result(doctors)
        )
        eval ($setDoctors.size() >= 3)
    	
    then
    
        System.out.println("ZAVISNIK "+  $p.getSurname() + " broj: "+ $listOfPrescriptions.size() );
    
    	stringSet.add(
	    	"Pacijent "+ $p.getName()+ " "+ $p.getSurname() +
	    	" je verovatno zavisan od analgetika "+
	    	" zato sto ga je u 6 meseci primion " + $listOfPrescriptions.size()+" puta "
	    	); 
    
end



rule "Slab imunitet "
agenda-group "imunitet"
    when
    	$p :Patient()
    	$listOfPrescriptions: List() from collect(
        	Prescription(
        		$p == patient,
        		medicine.medicineType == MedicineType.ANTIBIOTIK,
        		disease.timeStamp  > (nowGlobal - 12*30*24*36000*1000)
        	)
        )
    	eval($listOfPrescriptions.size() >= 10)
    	
    	$setDisease: Set() from accumulate(
            Prescription($d : disease) from $listOfPrescriptions,
            init(Set disease = new HashSet();),
            action(disease.add($d);),
            result(disease)
        )
        eval ($setDisease.size() >= 2)
        
        // Treba da nema ni jedno dodavanje leka a da nije antibiotik
        $listOfPrescriptionsWithoutAntibiotik: List() from collect(
        	Prescription(
        		$p == patient,
        		medicine.medicineType != MedicineType.ANTIBIOTIK,
        		disease.timeStamp  > (nowGlobal - 12*30*24*36000*1000)
        	)
        )
    	
    	eval($listOfPrescriptionsWithoutAntibiotik.size() == 0)
    	
    then
    
        System.out.println("SLAB IMUNINTET "+  $p.getSurname() + " broj: "+ $listOfPrescriptions.size() );
    
    	stringSet.add(
	    	"Pacijent "+ $p.getName()+ " "+ $p.getSurname() +
	    	" verovatno ima oslabljen imunitet "+
	    	" zato sto ga je u 12 meseci primion antibiotik " + $listOfPrescriptions.size()+" puta "
	    	); 
    
end

