//created on: Jun 11, 2018
package drools.spring.rules

//list any import classes here.
import drools.spring.example.symptom.Symptom;
import drools.spring.example.symptom.SymptomType;
import drools.spring.example.disease.Disease;
import drools.spring.example.disease.DiseaseType;
import drools.spring.example.prescription.Prescription;
import drools.spring.example.medicine.MedicineType;
import drools.spring.example.medicine.Medicine;
import drools.spring.example.medicine.Message;


//declare any global variables here

global Message customMessage;
global Long nowGlobal;
global java.util.List diseasesFount;


rule "Pacijenti sa hronicnim oboljenjima "
agenda-group "reports"
    when
    	$d :Disease( 
	    	$dt: diseaseType, 
	    	$p: patient,
	    	diseaseType != DiseaseType.PREHLADA,
	    	diseaseType != DiseaseType.GROZNICA,
	    	timeStamp  > (nowGlobal - 2*356*24*3600*1000)  
    	)
    	
    	$n: Number (intValue > 5) from accumulate(
        	$dis:Disease( $dt == diseaseType,
        		$p == patient,
        		timeStamp  > (nowGlobal - 2*356*24*3600*1000)
        	), count(1)
        )
    	
    then
    	boolean print = true;
    	for(Object di : diseasesFount){
    		Disease d = (Disease) di;
    		if( d.getPatient() == $p && d.getDiseaseType() == $d.getDiseaseType()){
    			print = false;
    		}
    	}
    	if(print){
	    	System.out.println("Pacijent "+ $p.getName()+ " " + $p.getSurname() +
	    		" verovatno hornicno boluje od " + $d.getDiseaseType());
	    	customMessage.message = customMessage.message + ","+
	    	"Pacijent "+ $p.getName()+ " "+ $p.getSurname() +
	    	" verovatno hornicno boluje od " + $d.getDiseaseType()+
	    	" zato sto je bolovao od nje " + $n+" puta u poslednjih 2 god";
	    	
	    	diseasesFount.add($d);
    	}
        
end