package drools.spring.example.symptom;

public enum SymptomType {
	// Prva grupa
	CURENJE_NOSA,BOL_U_GRLU,GLAVOBOLJA,KIJANJE,KASLJANJE,
	TEMPERATURA_38,CURENJE_IZ_NOSA,DRHTAVICA,
	BOL_KOJI_SE_SIRI_OKO_USIJU,TEMPERATURA_40_41,GUBLJENJE_APETITA,UMOR,ZUTI_SEKRET_IZ_NOSA,
	OTICANJE_OKO_OCIJU,I_PREHLADA_GROZNICA_60_DANA
	
	// Druga grupa
}
