package drools.spring.example.symptom;

public enum SymptomType {
	// Prva grupa
	CURENJE_NOSA,BOL_U_GRLU,GLAVOBOLJA,KIJANJE,KASLJANJE,
	TEMPERATURA_38,CURENJE_IZ_NOSA,DRHTAVICA,
	BOL_KOJI_SE_SIRI_OKO_USIJU,TEMPERATURA_40_41,GUBLJENJE_APETITA,UMOR,ZUTI_SEKRET_IZ_NOSA,
	OTICANJE_OKO_OCIJU,BOL_U_GLAVI,I_PREHLADA_GROZNICA_60_DANA,
	
	VISOK_PRITISAK,
	CESTO_URINIRANJE,GUBITAK_TELESNE_TEZINE,ZAMOR,MUCNINA_I_POVRACANJE,
	
	NOCTURIA,OTICANJE_NOGU_I_ZGLOBOVA,GUSENJE,BOL_U_GRUDIMA,
	OPORAVLJA_SE_OD_OPERACIJE,DIJAREJA,
	I_SPEC_HRONICNA_BUBREZNA,
	I_SPEC_AKUTNA_BUBREZNA,
	
	
	I_U_6_MESECI_10_PUTA_POVISE_PRITISAK,
	I_BOLUJE_OD_HIPERTENZIJE_VISE_OD_6_MESECI,
	I_BOLUJE_OD_DIJABETESA,
	I_U_POSLEDNJIH_14_DANA_VISOKA_TEMEPERATURA,
	I_U_POLSEDNJIH_21_DAN_PRIMAO_ANTIBIOTIKE
	
	
	
}
