package drools.spring.example.symptom;

public enum SymptomType {
	// Prva grupa
	CURENJE_NOSA,BOL_U_GRLU,GLAVOBOLJA,KIJANJE,KASLJANJE,
	TEMPERATURA_38,CURENJE_IZ_NOSA,DRHTAVICA,
	BOL_KOJI_SE_SIRI_OKO_USIJU,TEMPERATURA_40_41,GUBLJENJE_APETITA,UMOR,ZUTI_SEKRET_IZ_NOSA,
	OTICANJE_OKO_OCIJU,BOL_U_GLAVI,I_PREHLADA_GROZNICA_60_DANA,
	
	VISOK_PRITISAK,
	CESTO_URINIRANJE,GUBITAK_TELESNE_TEZINE,ZAMOR,MUCNINA_I_POVRACANJE
	
	// Druga grupa
}
